=== stretchyboy/cv/cv-schema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stylesheet/html_plain.xsl"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="cv">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="candidate"></xs:element>
        <xs:element ref="profile"></xs:element>
        <xs:element ref="experience" maxOccurs="1000"></xs:element>
        <xs:element ref="educationitem" maxOccurs="1000"></xs:element>
        <xs:element ref="referee" maxOccurs="1000"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="candidate">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"></xs:element>
        <xs:element ref="address"></xs:element>
        <xs:element name="mobile" type="xs:string"></xs:element>
        <xs:element name="email" type="xs:string"></xs:element>
        <xs:element name="twitter" type="xs:string"></xs:element>
        <xs:element name="linkedin" type="xs:string"></xs:element>
        <xs:element name="dateofbirth" type="xs:string"></xs:element>
        <xs:element name="nationality" type="xs:string"></xs:element>
        <xs:element name="maritalstatus" type="xs:string"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="line" type="xs:string" maxOccurs="1000"></xs:element>
        <xs:element name="city" type="xs:string"></xs:element>
        <xs:element name="postcode" type="xs:string"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="profile">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item" minOccurs="0" maxOccurs="1000"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="category" type="xs:string" minOccurs="0" maxOccurs="1000"></xs:element>
        <xs:element ref="description"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="description">
    <xs:complexType mixed="true">
      <xs:all>
        <xs:element ref="a" minOccurs="0" maxOccurs="1000"></xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>

   <xs:element name="a">
   <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="href" type="xs:string"></xs:attribute>
      </xs:extension>
    </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="organisation">
  <xs:complexType>
   <xs:simpleContent>
     <xs:extension base="xs:string">
       <xs:attribute name="href" type="xs:string"></xs:attribute>
     </xs:extension>
   </xs:simpleContent>
   </xs:complexType>
  </xs:element>

  <xs:element name="experience">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="organisation"></xs:element>
        <xs:element ref="date" maxOccurs="1000"></xs:element>
        <xs:element name="title" minOccurs="0" type="xs:string"></xs:element>
        <xs:element name="summary" minOccurs="0" type="xs:string"></xs:element>
        <xs:element ref="item" minOccurs="0" maxOccurs="1000"></xs:element>
        <xs:element name="departure" minOccurs="0" type="xs:string"></xs:element>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="date">
    <xs:complexType>
      <xs:attribute name="month" type="xs:string" use="required"></xs:attribute>
      <xs:attribute name="year" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="educationitem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="organisation"></xs:element>
        <xs:element ref="date" maxOccurs="1000"></xs:element>
        <xs:element ref="qualification" maxOccurs="1000"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="qualification">
    <xs:complexType>
      <xs:attribute name="grade" type="xs:string"></xs:attribute>
      <xs:attribute name="level" type="xs:string"></xs:attribute>
      <xs:attribute name="title" type="xs:string" use="required"></xs:attribute>
      <xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="referee">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="organisation"></xs:element>
        <xs:element ref="address"></xs:element>
        <xs:element name="tel" type="xs:string"  minOccurs="0"></xs:element>
        <xs:element name="email" type="xs:string"  minOccurs="0"></xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
      <xs:attribute name="title" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== stretchyboy/cv/xml/CurrentCV.xml
<?xml-stylesheet type="text/xsl" href="/home/meggleton/projects/cv/cv.xsl"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/meggleton/projects/cv/cv-schema2.xsd">
	<candidate>
		<name>Martyn Eggleton</name>
		<address>
			<line>118 Fairbarn Drive</line>
			<line>Stannington</line>
			<city>Sheffield</city>
			<postcode>S6 5QL</postcode>
		</address>
		<mobile>07927282148</mobile>
		<email>martyn.eggleton@gmail.com</email>
				<twitter>stretchyboy</twitter>
		<linkedin></linkedin>
		<dateofbirth>27th July 1976</dateofbirth>
		<nationality>British</nationality>
		<maritalstatus>Separated</maritalstatus>
	</candidate>
	<profile>
		
		<item>
			<category>System Design</category>
			<description>Flexible, adaptable and self developing with an aptitude for picking up ICT systems and techniques.</description>
		</item>
		<item>
			<category>Training</category>
			<description>Good training and development skills ranging from identifying learners needs to preparing sessions and giving feedback and assessment.</description>
		</item>
			<item>
			<category>Education</category>
			<description>Good classroom and workshop teaching skills and exposure to teacher training at <a href="http://shu.sc.uk">SHU</a> (Withdrew due to accidental injury).</description>
		</item>
		
		<item>
			<category>System Design</category>
			<description>A keen free and open source software developer who contributes to and leads various small FLOSS projects..</description>
		</item>
		<item>
			<category>Community</category>
			<description>A keen free and open source software developer who contributes to and leads various small FLOSS projects..</description>
		</item>
		<item>
			<category>Programming</category>
			<description>A skilled programmer with over 13 years experience in web technologies especially  HTML, JavaScript, PHP and Node.js.</description>
		</item>
		<item>
			<category>Mozilla</category>
			<description>Involved in delivering the children's activities at each  <a href="https://mozillafestival.org/">MozFest</a> since 2012. </description>
		</item>
		<item>
			<category>Mozilla</category>
			<description>Hoping to be on the next Mozilla Open Leadership Training course. </description>
		</item>
		
		<item>
			<category>System Design</category>
			<description>Dedicated to bringing the most efficient and usable user experience to new and existing systems, by bring forward innovative ideas and developing them into complete systems.</description>
		</item>
		<item>
			<category>PHP</category>
			<description>A hardworking individual with experience of working in small teams as well as written, verbal and visual communication.</description>
		</item>
		<item>
			<description>An aptitude for software development, systems design, education and training.</description>
		</item>
		
		<item>
			<description>A hardworking individual with good interpersonal, written, verbal and visual communications skills and an aptitude for software development, employment advice, training and coaching.</description>
		</item>
		
		<item>
			<category>PHP</category>
			<description>Good awareness of design, planning &amp; problem solving
    techniques and approaches in a variety of situations from developing functional specifications
    for technical solutions with users, to process development, training, team and capacity building.</description>
		</item>
		<item>
			<description>Good desktop publishing and web development skills both aesthetically and technically, with a strong commitment to clean code.</description>
		</item>
		<!--<item>
			<description>Flexible, adaptable and self developing with an aptitude for picking up ICT systems and techniques
			 (I am currently learning JAVA for 3D games development and XUL for an Internet aware song lyric and presentation projection suite).</description>
		</item>-->
		<item>
			<description>Good training and development skills ranging from identifying learners needs to preparing sessions and giving feedback and assessment.</description>
		</item>
		<item>
			<description>Experience of high profile and high financial turnover environments, writing for systems with an annual turnover in excess of  14 million pounds 
			and being the mostly responsible for the 'Flora London Marathon Exhibition' website.</description>
		</item>
	</profile>


	<experience type="Paid">
		<organisation>Sheffield University Technical College</organisation>
	
		<date year="2013" month="09"></date>
	
		<title>Skills Trainer, Creative Digital Media &amp;  Computing</title>
		<item>
			<category>System Design</category>
			<description>Part of co-design process for a new PlayStation VR, Educational Environmental Narrative game as part of the  <a href="http://revealvr.eu">REVEAL</a> project with SHU.</description>
		</item>
		<item>
			<category>Education</category>
			<description>Teaching GCSE Computing to various groups  Explaining both the theory of computer science and the practicalities of programming.</description>
		</item>
		<item>
			<category>Education</category>
			<description>Teaching version control, team working technologies (git, issue tracking etc.) and test driven development, mostly in JavaScript.</description>
		</item>
		<item>
			<category>Education</category>
			<description>Project mentor on student led projects using a wide range of technologies, including dancing drone, importing LIDAR data into MineCraft and mapping.</description>
		</item>
				<item>
			<category>Education</category>
			<description>Heavily used Raspberry Pi for teaching of theory, physical computing and engineering. 
			Using and contributing to the PiNet community and building tools like logicexplorer, a physical logic gate / circuit simulator.</description>
		</item>
<item>
			<category>Teaching</category>
			<description>Lead teaching of 3 cohorts of GCSE Computing, including tracking and student / parent feedback.</description>
		</item>
	</experience>

	<experience type="Paid">
		<organisation>EduMake</organisation>
	
		<date year="2012" month="05"></date>
	
		<title>Learning Technologist</title>
		<item>
			<category>Emerging Tech</category>
				<category>JavaScript</category>
			<description>Building Amazon Alexa Skill and learning materials for other to make their own for free.</description>
		</item>
		<item>
			<category>JavaScript</category>
			<description>Designed the software of  <a href="http://junctionarts.org/data-draw/">Data-Draw</a> a machine for capturing survey data in a tactile and engaging way. 
			It then produces unique custom art from the data, for the individual both on paper and the web and for the whole event online..</description>
		</item>
		<item>
			<category>JavaScript</category>	<category>Education</category>
			<description>Built active_learn and active_JavaScript adaptive learning environments, which give differentiated learning paths way for 
			Computing Maths skills and JavaScript programming skills.</description>
		</item>
	</experience>



	<experience type="Paid">
		<organisation>Access-Space</organisation>
		<date year="2009" month="01"></date>
		<date year="2013" month="04"></date>
		<title>Technical Officer</title>
		<item>
			<category>Linux</category>
			<description>Teaching workshops with Access-Space users new to Linux and FOSS on how to choose install and configure a GNU/Linux distribution,</description>
		</item>
				<item>
			<category>Linux</category>
			<description>Built hardware auditing linux distro with hardware testing and recording, using bash scripting etc.</description>
		</item>
		<item>
			<category>Hardware</category>
			<description>Teaching customers how to build PCs to fit their needs from recycled parts..</description>
		</item>
		<item>
			<category>Community</category>
			<description>Working within a community setting and leading the volunteer hardware team.</description>
		</item>
		<item>
			<category>PHP</category>
			<description>Built various DokuWiki plugins in PHP.</description>
		</item>
		<item>
			<category>PHP</category>
			<description>Developed light touch peer learning tracking software for monitoring and reporting of the progress of informal learning networks.</description>
		</item>
		<item>
			<category>Software</category>
			<description>Sharing knowledge of Free/Libre Open Source Software, philosophy utilities and tools (and the ethos behind them) for development with other users including creativity programs, 
			editors and programming libraries.</description>
		</item>
		<item>
			<description>Excellent Communication Skills</description>
		</item>
		<item>
			<category>Documentation</category>
			<description>A wide range of writing styles from reports through to simple how to documents</description>
		</item>
		<item>
			<description>The ability to self manage and prioritise own workload</description>
		</item>
		<item>
			<description>Excellent time management</description>
		</item>

		<item>
			<category>WebDev</category>
			<description>Assisting in the creation of various Access-Space Web pages including modifying HTML templates for dokuwiki.</description>
		</item>
	</experience>


	<experience type="Voluntary">
		<organisation>Access-Space</organisation>
		<date year="2008" month="12"></date>
		<date year="2008" month="07"></date>
		<title>Training / Technical Volunteer</title>
		<item>
			<category>Linux</category>
			<description>Teaching workshops with Access-Space users new to Linux and FOSS on how to choose install and configure a GNU/Linux distribution, using course notes I wrote in preparation (http://knowhow.access-space.org/wiki/doku.php?id=courses:ilit).</description>
		</item>
		<item>
			<category>Hardware</category>
